<?php

require_once __DIR__ . '/mock/Controller.php';

use Minity\Controller\ActionFactory;

/**
 * Test class for ActionFactory.
 * Generated by PHPUnit on 2012-03-10 at 22:21:49.
 */
class ActionFactoryTest extends PHPUnit_Framework_TestCase
{
    public function testBuild()
    {
        $services = $this->getMock('Minity\Service\Container');
        $request  = $this->getMock(
            'Minity\Http\Request',
            array(),
            array(array(),array(),array())
        );
        $factory = new ActionFactory($services, $request);
        $controller = $factory->create('Default', 'index');
        $this->assertInstanceOf('DefaultController', $controller);
    }
}
