<?php

use Minity\Http\Response;

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-03-10 at 01:41:00.
 */
class HttpResponseTest extends PHPUnit_Framework_TestCase
{

    public function testSetAndGetHeader()
    {
        $response = new Response('');
        $response->setHeader('Content-type', 'text/javascript');
        $this->assertEquals(
            'text/javascript',
            $response->getHeader('Content-type')
        );
    }

    public function testSend()
    {
        $response = new Response('text');

        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals('text', $response->getContent());
        $response->setStatusCode(500);
        $response->setContent('error');
        $this->assertEquals(500, $response->getStatusCode());
        $this->assertEquals('error', $response->getContent());

        ob_start();
        $response->send();
        $content = ob_get_clean();
        $this->assertEquals('error', $content);
    }
}
