<?php

require_once __DIR__ . '/mock/Controller.php';

use Minity\Controller\Router;

/**
 * Test class for Router.
 * Generated by PHPUnit on 2012-03-09 at 14:58:38.
 */
class RouterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException RuntimeException
     */
    public function testCreateWrongActionDefinition()
    {
        $rules = array(
            'mainpage' => array(
                'url'    => '/',
                'action' => 'Default'
            ),
        );
        new Router($rules);
    }

    public function testMatch()
    {
        $rules = array(
            'mainpage' => array(
                'url'    => '/',
                'action' => 'Default:index'
            ),
            'listpage' => array(
                'url'    => '/list',
                'action' => 'Default:list'
            ),
        );
        $router = new Router($rules);
        $routeResult = $router->match('/list');
        $expected = array(
            'url'        => '/list',
            'controller' => 'Default',
            'action'     => 'list',
            'params'     => array()
        );
        $this->assertEquals($expected, $routeResult);
        $routeResult = $router->match('/');
        $expected = array(
            'url'        => '/',
            'controller' => 'Default',
            'action'     => 'index',
            'params'     => array()
        );
        $this->assertEquals($expected, $routeResult);
    }

    /**
     * @expectedException \Minity\Http\NotFoundException
     */
    public function testNotMatch()
    {
        $rules = array(
            'mainpage' => array(
                'url'    => '/',
                'action' => 'Default:index'
            ),
        );
        $router = new Router($rules);
        $router->match('/list');
    }

    public function testGenerate()
    {
        $rules = array(
            'mainpage' => array(
                'url'    => '/',
                'action' => 'Default:index'
            ),
        );
        $router = new Router($rules);
        $this->assertEquals(
            '/',
            $router->generate('mainpage')
        );
        $this->assertEquals(
            '/?a=10&b%5B1%5D=qwer&b%5B2%5D=tyu',
            $router->generate(
                'mainpage',
                array(
                    'a' => 10,
                    'b' => array(
                        1 => 'qwer',
                        2 => 'tyu',
                    )
                )
            )
        );
    }

    /**
     * @expectedException OutOfRangeException
     */
    public function testGenerateInternal()
    {
        $rules = array(
            'special' => array(
                'action' => 'Default:index'
            ),
        );
        $router = new Router($rules);
        $router->generate('special');
    }

    /**
     * @expectedException OutOfBoundsException
     */
    public function testGenerateUnexistent()
    {
        $rules = array();
        $router = new Router($rules);
        $router->generate('mainpage');
    }
}
